version: "3"
services:
  mymongodb:
    image: mongo:latest
    container_name: "mymongodb"
    ports:
      - 27017:27017
  springboot-mongodb:
    image: hendisantika/springboot-mongodb-docker-compose:latest
    container_name: springboot-mongodb-docker-compose
    ports:
      - 8081:8080
    links:
      - mymongodb