version: "3"
services:
  mymongodb:
    image: mongo:latest
    container_name: "mymongodb"
    ports:
      - 27017:27017
  springboot-mongodb:
    image: springboot-mongodb-docker-compose:1.0
    container_name: springboot-mongodb-docker-compose
    ports:
      - 8080:8080
    links:
      - mymongodb